name: Bug report
description: Create a report to help us improve
#title: ''
#labels: ['']
#assignees: []

body:
  - type: textarea
    id: pihole-version
    attributes:
      label: Versions
      description: "Please run `pihole -v` and provide the following"
      placeholder: |
        - Pi-hole:  
        - AdminLTE:  
        - FTL:  
      render: shell
    validations:
      required: true

  - type: input
    id: os-version
    attributes:
      label: Operating System and Version
      description: "Examples of OS: Debian 10, Debian Buster, Ubuntu 18.04"
      placeholder: "e.g., Ubuntu 20.04"
    validations:
      required: true

  - type: input
    id: platform
    attributes:
      label: Platform
      description: "Examples of platforms: Raspberry Pi, Docker, Synology, VM/VPS"
      placeholder: "e.g., Raspberry Pi 4"
    validations:
      required: true

  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected Behavior
      description: "A clear and concise description of what you expected to happen."
      placeholder: "I expected that..."
    validations:
      required: true

  - type: textarea
    id: actual-behavior
    attributes:
      label: Actual Behavior / Bug
      description: "A clear and concise description of what the bug is."
      placeholder: "The bug occurs when..."
    validations:
      required: true

  - type: textarea
    id: reproduce-steps
    attributes:
      label: Steps to Reproduce
      description: "Steps to reproduce the behavior:"
      placeholder: "1. Go to '...'\n2. Click on '....'\n3. Scroll down to '....'\n4. See error"
    validations:
      required: true

  - type: input
    id: debug-token
    attributes:
      label: Debug Token
      description: "The URL of the debug token generated by running `pihole -d`."
      placeholder: "e.g., https://tricorder.pi-hole.net/wim5hft4rq"
    validations:
      required: false

  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots
      description: "If applicable, add screenshots to help explain your problem."
      placeholder: "Upload your screenshot here." 
    validations:
      required: false

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: "Add any other context about the problem here."
      placeholder: "Further information..."
    validations:
      required: false
